server:
  port: 8090
  servlet:
    context-path: /api

spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, zxw
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
    sentinel:
      transport:
        dashboard: localhost:8080   #这个是 sentinel 控制台(sentinel dashboard)的地址
        # 解读spring.cloud.sentinel.transport.port
        #1. spring.cloud.sentinel.transport.port 端口配置会在被监控的微服务;对应的机器上启动一个 HttpServer
        #2. 该 Server 会与 Sentinel 控制台做交互
        #3. 比如 Sentinel 控制台添加了1个限流规则，会把规则数据 push 给这个
        #   Http Server 接收，Http Server 再将规则注册到 Sentinel 中
        #4. 简单的说明:spring.cloud.sentinel.transport.port: 指定被监控的微服务应用与
        #   Sentinel 控制台交互的端口，微服务应用本地会起一个该端口占用的HttpServer
        port: 8719
      enabled: true
      datasource:
        gateway-sentinel-flow-control-nacos-rule: #自定义数据源名称: #自定义数据源名称
          nacos:
            server-addr: http://localhost:8848
            namespace:   # 需要配置该规则所在的命名空间
            data-id: user-interfaceInfo-invoke-global-filter-invokeInterfaces-rule # 所配置的id
            rule-type: flow # 规则类型
            data-type: json # 默认值是 json.

      #        - id: path_route
      #          uri: https://baidu.com
      #          predicates:
      #            - Path=/api/**
      #
      #        - id: path_route2
      #          uri: https://bing.com
      #          predicates:
      #            - Path=/baidu/**

      #        - id: before_route
      #          uri: https://baidu.com
      #          predicates:
      #            - After=2024-11-28T17:42:47.789-07:00[America/Denver]




    #        降级：
    #        - id: add_request_header_route
    #          uri: http://localhost:8123
    #          predicates:
    #            - Path=/api/**
    #          filters:
    #            - AddRequestHeader=zxw,swag
    #            - AddRequestParameter=name,king
    #            # - CircuitBreaker=myCircuitBreaker
    #            - name: CircuitBreaker
    #              args:
    #                name: myCircuitBreaker
    #                fallbackUri: forward:/fallback
    #                  - RewritePath=/consumingServiceEndpoint, /backingServiceEndpoint
    #        - id: zxw-fallback
    #          uri: http://baidu.com
    #          predicates:
    #            - Path=/fallback
dubbo:
  application:
    name: open_api-backend
  protocol:
    host: 127.0.0.1
    name: dubbo
    port: -1    # 随机端口
  registry:
    address: nacos://localhost:8848
    id: nacos-registry
  cache:
    # 更改缓存目录
    file: D:/mavenn/.m2/.dubbo.bak



logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'


